### ISSUE TITLE
Останавливается на этапе получения письма с активацией

### ISSUE THREAD

**Issue by 3soolo3** [Notheireat/DIPlaylist#2]
Останавливается на этапе получения письма с активацией
![default](https://user-images.githubusercontent.com/16206472/41140951-d8cf2a8a-6af8-11e8-80b1-ed4b85cab30c.png)
![1](https://user-images.githubusercontent.com/16206472/41140955-dc6f4526-6af8-11e8-8920-7e99ce95a664.png)

**Comment by Notheireat** [comment]
Да, я уже видел эту ошибку. Проблема в том, что с сайта di.fm перестало приходить письмо после регистрации на сайте. Проверял на нескольких почтовых сервисах, никуда письмо так и не пришло.

**Comment by Notheireat** [comment]
На текущий момент письмо вновь начало приходить, но уже иного содержания. И теперь, там вот что: "As a new member, you're entitled to 30 days of DI.FM Premium, our upgraded service that eliminates the commercials and boosts your audio quality. Activate your exclusive 30-Day Free Trial by downloading the DI.FM mobile app and visiting the Premium page in the app". 
Таким образом, премиум как раньше - активировать уже не получится. Посмотрим, что изменится спустя какое-либо количество времени...

**Comment by 3soolo3** [comment]
Хм. Ясно. Прикрыли халяву
